-- Autocompletion
return {
	-- "hrsh7th/nvim-cmp",
	-- dependencies = {
	-- 	{ "hrsh7th/cmp-buffer" },
	-- 	{ "hrsh7th/cmp-path" },
	-- 	{ "hrsh7th/cmp-cmdline" }, -- gives vim command line auto completion
	-- 	{ "saadparwaiz1/cmp_luasnip" },
	-- 	{ "hrsh7th/cmp-nvim-lsp" }, -- auto completion glue
	-- 	{ "hrsh7th/cmp-nvim-lua" },
	--
	-- 	-- Snippets
	-- 	{
	-- 		"L3MON4D3/LuaSnip",
	-- 		version = "v2.1.1",
	-- 		build = "make install_jsregexp",
	-- 		dependencies = { "rafamadriz/friendly-snippets" },
	-- 	},
	-- },
	--
	-- config = function()
	-- 	require("./plugins/configs/cmp")
	-- end,
}
